import os
import time
import pyautogui


# def facebook():
#     facebook_range = int(input("Enter how many names you have in the file: "))
#     facebook_file = input("Enter the file that have names: ")
#     facebook_message = input("Enter the file that have message: ")
#     facebook_object = open(facebook_file)
#     os.system(f"start {facebook_message}")
#     pyautogui.keyDown("alt")
#     pyautogui.keyDown("tab")
#     pyautogui.keyUp("alt")
#     pyautogui.keyUp("tab")
#     pyautogui.keyDown("ctrl")
#     pyautogui.keyDown("a")
#     pyautogui.keyUp("ctrl")
#     pyautogui.keyUp("a")
#     pyautogui.keyDown("ctrl")
#     pyautogui.keyDown("c")
#     pyautogui.keyUp("ctrl")
#     pyautogui.keyUp("c")
#     for _ in range(facebook_range):
#         os.system(f"start https://www.messenger.com/")
#         time.sleep(10)
#         pyautogui.click(x=1788, y=200)# for search
#         pyautogui.click(x=1788, y=200) # for search
#         time.sleep(5)
#         pyautogui.typewrite(facebook_object.readline())
#         time.sleep(8)
#         pyautogui.click(x=1776, y=251) # for take one Account
#         time.sleep(1)
#         pyautogui.keyDown("ctrl")
#         pyautogui.keyDown("v")
#         pyautogui.keyUp("ctrl")
#         pyautogui.keyUp("v")
#         time.sleep(7)
#         pyautogui.keyDown("enter")
#         pyautogui.keyUp("enter")
#     facebook_object.close()


def whatsapp():
    whatsapp_range = int(input("Enter how many numbers you have in the file: "))
    whatsapp_file = input("Enter the file that have the numbers: ")
    whatsapp_message = input("Enter the file that have your message: ")
    whatsapp_object_ = open(whatsapp_file)
    os.system(f"start {whatsapp_message}")
    pyautogui.keyDown('alt')
    pyautogui.keyDown('tab')
    pyautogui.keyUp('alt')
    pyautogui.keyUp('tab')
    pyautogui.keyDown("ctrl")
    pyautogui.keyDown("a")
    pyautogui.keyUp("ctrl")
    pyautogui.keyUp("a")
    pyautogui.keyDown("ctrl")
    pyautogui.keyDown("c")
    pyautogui.keyUp("ctrl")
    pyautogui.keyUp("c")
    
    for _ in range(whatsapp_range):
        os.system(f"start chrome.exe https://web.WhatsApp.com/send?phone={whatsapp_object_.readline()}")
        time.sleep(14)
        pyautogui.click(x=1033, y=995)
        pyautogui.keyDown("ctrl")
        pyautogui.keyDown("v")
        pyautogui.keyUp("ctrl")
        pyautogui.keyUp("v")
        time.sleep(5)
        pyautogui.keyDown("enter")
        pyautogui.keyUp("enter")
    whatsapp_object_.close()
 

def Instagram():
    Instagram_range = int(input("Enter how many ids you have : "))
    Instagram_file = input("Enter the file that have ids : ")
    Instagram_message = input("Enter the file that have message: ")
    Instagram_object = open(Instagram_file)
    os.system(f"start {Instagram_message}")
    pyautogui.keyDown('alt')
    pyautogui.keyDown('tab')
    pyautogui.keyUp('alt')
    pyautogui.keyUp('tab')
    pyautogui.keyDown("ctrl")
    pyautogui.keyDown("a")
    pyautogui.keyUp("ctrl")
    pyautogui.keyUp("a")
    pyautogui.keyDown("ctrl")
    pyautogui.keyDown("c")
    pyautogui.keyUp("ctrl")
    pyautogui.keyUp("c")
    for _ in range(Instagram_range):
        os.system(f"start chrome.exe https://www.instagram.com/direct/new")
        time.sleep(10)
        pyautogui.typewrite(Instagram_object.readline())
        time.sleep(8)
        pyautogui.click(x=953, y=469)
        pyautogui.click(x=1123, y=358)
        time.sleep(5)
        pyautogui.click(x=1004, y=980)
        pyautogui.keyDown("ctrl")
        pyautogui.keyDown("v")
        pyautogui.keyUp("ctrl")
        pyautogui.keyUp("v")
        time.sleep(7)
        pyautogui.keyDown('enter')
        pyautogui.keyUp('enter')
    Instagram_object.close()



def __markting__():
    def whatsapp__web():
        whatsapp_web = input(" do you sign in a whastapp web y or n >>> ")
        if whatsapp_web == 'y':
            pass
        elif whatsapp_web == 'n':
            os.system("start chrome.exe web.whatsapp.com")
        else:
            whatsapp__web()

    whatsapp__web()
    print("[1] Whatsapp""   ""[2] Instagram")
    markting = input("Enter the social that you want >>> ")
    if markting == '1':
        def __whatsapp_photo__():
            whatsapp_want_photo = input("do you want to add a photo? y or n ")
            if whatsapp_want_photo == 'y':
                whatsapp_photo = input("Enter the path of photo : ")
                whatsapp_photo_ = input("Enter the photo name : ")
                whatsapp_photo_range = int(input("Enter how many numbers you have ? "))
                whatsapp_photo_file = input("Enter the file that have numbers: ")
                whatsapp_photo_object = open(whatsapp_photo_file)
                whatsapp_message_photo  = input("Enter the message file: ")
                os.system(f"start {whatsapp_message_photo}")
                pyautogui.keyDown('alt')
                pyautogui.keyDown('tab')
                pyautogui.keyUp('alt')
                pyautogui.keyUp('tab')
                pyautogui.keyDown("ctrl")
                pyautogui.keyDown("a")
                pyautogui.keyUp("ctrl")
                pyautogui.keyUp("a")
                pyautogui.keyDown("ctrl")
                pyautogui.keyDown("c")
                pyautogui.keyUp("ctrl")
                pyautogui.keyUp("c")
                for _ in range(whatsapp_photo_range):
                    os.system(f"start chrome.exe https://web.WhatsApp.com/send?phone={whatsapp_photo_object.readline()}")
                    time.sleep(14)
                    pyautogui.click(x=763, y=994)
                    pyautogui.click(x=763, y=934)
                    time.sleep(5)
                    pyautogui.keyDown("ctrl")
                    pyautogui.keyDown("l")
                    pyautogui.keyUp("ctrl")
                    pyautogui.keyUp("l")
                    pyautogui.typewrite(whatsapp_photo)
                    time.sleep(4)
                    pyautogui.click(x=412, y=474)
                    time.sleep(0.5)
                    pyautogui.typewrite(whatsapp_photo_)
                    time.sleep(0.4)
                    pyautogui.keyDown("enter")
                    pyautogui.keyUp("enter")
                    time.sleep(5)
                    pyautogui.keyDown("ctrl")
                    pyautogui.keyDown("v")
                    pyautogui.keyUp("ctrl")
                    pyautogui.keyUp("v")
                    time.sleep(5)
                    pyautogui.keyDown("enter")
                    pyautogui.keyUp("enter")
            elif whatsapp_want_photo == 'n':
                whatsapp()
            else:
                print("pleas Enter y or n")
                __whatsapp_photo__()
        __whatsapp_photo__()

        whatsapp()
    elif markting == '2':
        def Instagram_photo():
            want_instagram_photo = input("do you want to add a photo? y or n ")
            if want_instagram_photo == 'y':
                Instagram_photo = input("Enter the path of the photo : ")
                Instagram_photo_ = input("Enter the name of the photo: ")
                Instagram_photo_range = int(input("Enter how many ids you have ? "))
                Instagram_photo_file = input("Enter the file that have ids: ")
                Instagram_photo_object = open(Instagram_photo_file)
                Instagram_message_photo  = input("Enter the message file: ")
                os.system(f"start {Instagram_message_photo}")
                pyautogui.keyDown('alt')
                pyautogui.keyDown('tab')
                pyautogui.keyUp('alt')
                pyautogui.keyUp('tab')
                pyautogui.keyDown("ctrl")
                pyautogui.keyDown("a")
                pyautogui.keyUp("ctrl")
                pyautogui.keyUp("a")
                pyautogui.keyDown("ctrl")
                pyautogui.keyDown("c")
                pyautogui.keyUp("ctrl")
                pyautogui.keyUp("c")
                for _ in range(Instagram_photo_range):
                    os.system(f"start chrome.exe https://www.instagram.com/direct/new")
                    time.sleep(10)
                    pyautogui.typewrite(Instagram_photo_object.readline())
                    time.sleep(8)
                    pyautogui.click(x=953, y=469)
                    pyautogui.click(x=1123, y=358)
                    time.sleep(5)
                    pyautogui.click(x=1316, y=970)
                    time.sleep(4)
                    pyautogui.keyDown("ctrl")
                    pyautogui.keyDown("l")
                    pyautogui.keyUp("ctrl")
                    pyautogui.keyUp("l")
                    pyautogui.typewrite(Instagram_photo)
                    time.sleep(0.5)
                    pyautogui.click(x=255, y=476)
                    time.sleep(0.5)
                    pyautogui.typewrite(Instagram_photo_)
                    pyautogui.keyDown("enter")
                    pyautogui.keyUp("enter")
                    time.sleep(1)
                    pyautogui.keyDown("ctrl")
                    pyautogui.keyDown("v")
                    pyautogui.keyUp("ctrl")
                    pyautogui.keyUp("v")
                    time.sleep(7)
                    pyautogui.keyDown('enter')
                    pyautogui.keyUp('enter')
            elif want_instagram_photo == 'n':
                Instagram()
            else:
                print('pleas Enter y or n')
                Instagram_photo()

        Instagram_photo()
    # elif markting == '3':
    #     def __facebook_want_photo_():
    #         facebook_want_photo = input("do you want a photo ? y or n  ")
    #         if facebook_want_photo == 'y':
    #             facebook_photo_path = input("Enter the path of the photo: ")
    #             facebook_photo_name = input("Enter the name of the photo: ")
    #             facebook_photo_range = int(input("Enter how many names you have in the file: "))
    #             facebook_photo_file = input("Enter the file that have names: ")
    #             facebook_photo_message = input("Enter the file that have message: ")
    #             facebook_photo_object = open(facebook_photo_file)
    #             os.system(f"start {facebook_photo_message}")
    #             pyautogui.keyDown("alt")
    #             pyautogui.keyDown("tab")
    #             pyautogui.keyUp("alt")
    #             pyautogui.keyUp("tab")
    #             pyautogui.keyDown("ctrl")
    #             pyautogui.keyDown("a")
    #             pyautogui.keyUp("ctrl")
    #             pyautogui.keyUp("a")
    #             pyautogui.keyDown("ctrl")
    #             pyautogui.keyDown("c")
    #             pyautogui.keyUp("ctrl")
    #             pyautogui.keyUp("c")
    #             for _ in range(facebook_photo_range):
    #                 os.system(f"start https://www.messenger.com/")
    #                 time.sleep(10)
    #                 pyautogui.click(x=1788, y=200)
    #                 pyautogui.typewrite(facebook_photo_object.readline())
    #                 time.sleep(8)
    #                 pyautogui.click(x=1136, y=1011)
    #                 time.sleep(5)
    #                 pyautogui.click(x=1492, y=1004)
    #                 time.sleep(0.5)
    #                 pyautogui.keyDown("ctrl")
    #                 pyautogui.keyDown("l")
    #                 pyautogui.typewrite(facebook_photo_path)
    #                 time.sleep(1)
    #                 pyautogui.click(x=377, y=477)
    #                 pyautogui.typewrite(facebook_photo_name)
    #                 time.sleep(1)
    #                 pyautogui.keyDown("enter")
    #                 pyautogui.keyUp("enter")
    #                 time.sleep(1)
    #                 pyautogui.keyDown("ctrl")
    #                 pyautogui.keyDown("v")
    #                 pyautogui.keyUp("ctrl")
    #                 pyautogui.keyUp("v")
    #                 time.sleep(5)
    #                 pyautogui.keyDown("enter")
    #                 pyautogui.keyUp("enter")
    #         elif facebook_want_photo == 'n':
    #             facebook()
    #         else:
    #             print("y or n")
    #             __facebook_want_photo_()
    #     __facebook_want_photo_()

    else:
        print("pleas Enter 1 or 2 ")
        time.sleep(0.3)
        __markting__()


__markting__()

exit()
